# Generated by Django 5.1.6 on 2025-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edusco', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('visitor', 'Visitor')], default='visitor', max_length=10),
        ),
    ]
